model_name: "THUDM/cogagent-chat-hf"
# TODO actual paths for train / test
train_screenshots_txt: data/training/screenshots.txt
test_screenshots_txt: data/testing/screenshots.txt
train_labels_txt: data/training/labels.txt
save_path: results
max_tokens: 2000 # normally less than 4000
in_context_learning: true # flag to use in context learning for fine tuning
temperature_majority_voting: 0.5 # normally less than 1
temperature_self_reflect: 0.1 # normally less than 1
top_p_majority_voting: 0.5 # normally less than 1
top_p_self_reflect: 0.9 # normally less than 1
repetition_penalty_majority_voting: 1.0
repetition_penalty_self_reflect: 1.0
majority_voting_candidates: 5 # number of candidates for majority voting, if it is 1, it will not use majority voting
image_resize: [1120, 1120] # [width, height]
use_self_reflect: true # when used, it will use the self-reflect mechanism
debug_mode: true # when used, it will only test on the last video of the testing videos
prompts:
  system: >
    You are a labelling assistant to label the user interactions with the screen for every screenshot in the chronological screenshots.
    Each screenshot is a state of the screen at a certain time. The label for each state should only describe the user's last actions which changed the last state of the screen to the current state of the screen. 
    Each screenshot should have one label. In each label, describe: the user action just happened, the screen display change, and the current screen display.
    Do not skip any intermediate actions.
    Be specific, precise and accurate.
  training_example: >
    The following is {number_frames} chronological screenshots and their labels:
  testing_example: >
    The following is {number_frames} chronological screenshots to be labelled.
  reflection: >
    The initial prediction is:
    {initial_prediction}
    Please review the screenshots and their prediction. Provide an improved version of the prediction if necessary.
  question: >
    Please provide the labels for each state in the above screenshots by fulfilling the beneath template:
