model_name: "gpt-4o-mini" # gpt-4o-mini
api_key: sk-proj-ZxH9n4f7EHjWlCBo0bdjT3BlbkFJzpfDqdqNHisk1b56DZoM # Ask Sam for your api key
# api_key: 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
# train_screenshots_txt: /home/moucheng/projects/screen_action_labels/data/split/Wonderbread/1723811870.4719887/training_data_bs8_sd42/batch_1.txt
train_screenshots_txt: /home/moucheng/projects/screen_action_labels/data/split/Wonderbread/1723811870.4719887/training_data_bs8_sd42/batch_1.txt
test_screenshots_txt: /home/moucheng/projects/screen_action_labels/data/split/Wonderbread/1723811870.4719887/testing/screenshots.txt # change this to your own path
resume_testing_path: /home/moucheng/projects/screen_action_labels/results/1724922859/Wonderbread/gold_demos
save_path: ../../results # change this to your own path
max_tokens: 4096 # 
effective_train_videos_number: 8
timeout: 2000.0
in_context_learning: true # flag for using few shot learning
temperature_majority_voting: 0.5 # normally less than 1
temperature_self_reflect: 0.1 # normally less than 1
top_p_majority_voting: 0.95 # normally less than 1
top_p_self_reflect: 0.95 # normally less than 1
majority_voting_candidates: 1 # number of candidates for majority voting, if it is 1, it will not use majority voting
image_resize: [1024, 768] # [width, height] [1024, 768]
use_self_reflect: false # when used, it will use the self-reflect mechanism
debug_mode: false # when used, it will only test on the last video of the testing videos
prompts: 
  system: > 
   Your job is to write a standard operating procedure (SOP) for a workflow based on the given screenshots.
   The SOP should contain a numerated list of actions taken by the user to complete the given workflow.
  training_example: >
    Here are a sequence of screenshots of the workflow:
  testing_example: >
    You are given the following sequence of screenshots which were sourced from a demonstration of the workflow. 
    The screenshots are presented in chronological order.
    Here are the screenshots of the workflow:
  reflection: >
    The initial prediction is:
    {initial_prediction}
    Please review your prediction. Provide an improved version of the prediction if necessary.
  question: >
    Given what you observe in the sequence of actions, write an SOP for completing the workflow. 
    The SOP should simply contain an enumerated list of actions taken by the user to complete the given workflow.
    In your SOP, list all of the actions taken (i.e., buttons clicked, fields entered, mouse scrolls etc.). 
    Be descriptive about elements (i.e., 'the subheading located under the "General" section'). 
    Use the location of the mouse to identify which exact elements were clicked.
    Here is a sample format for what your SOP should look like:
    1. Type the name of the repository in the search bar at the top left of the screen. The placeholder text in the search bar is "Find a repository...", and it is located directly to the right of the site logo.
    2. A list of repositories will appear on the next page. Scroll down until you see a repository with the desired name. The name of the repository will be on the lefthand side of the row in bold font. Stop when you find the name of the repository.
    3. Click on the relevant repository to go to the repository's main page.
    Note, the above SOP is just an example. Use the same format, but the actions will be different for your workflow.
    Be as detailed as possible. Each step should be a discrete action that reflects what you see in the corresponding step. Don't skip steps.
    Please write your SOP below:
